//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_64131196.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Congnghephanmem_64131196Entities : DbContext
    {
        public Congnghephanmem_64131196Entities()
            : base("name=Congnghephanmem_64131196Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<DatLichPT> DatLichPT { get; set; }
        public virtual DbSet<GoiTap> GoiTap { get; set; }
        public virtual DbSet<HuanLuyenVien> HuanLuyenVien { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<LichLamViecPT> LichLamViecPT { get; set; }
        public virtual DbSet<NguoiQuanTri> NguoiQuanTri { get; set; }
        public virtual DbSet<VaiTro> VaiTro { get; set; }
    }
}
