//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_64131196.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiQuanTri
    {
        public int ID { get; set; }
        public string Ten { get; set; }
        public Nullable<int> MaVaiTro { get; set; }
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
    
        public virtual VaiTro VaiTro { get; set; }
    }
}
